Implemented backend for Trip Photos (w/ Azure Blob Storage)
jmoran-cei/TravelTrack-API pull request #7
Opened 2023-01-26 21:27 UTC by jmoran-cei

- added trip photo domain model & DTO
- updated DB context & added migration w/ seed data
- implemented `BlobService` to utilize Azure Blob Storage for uploading/deleting photo files
- added new methods to `TripController` & `TripService`
  - `AddPhotoToTrip`: uploads file to blob storage & saves it to a trip => returns updated trip
  - `RemovePhotosFromTrip`: iterates to remove each photo file from blob storage and from the DB ==> return updated trip

----------

Note: Haven't completed new tests yet, because of prioritizing the frontend at the moment.

2023-02-01 13:41 UTC, swhook52 requested changes

2023-02-01 13:41 UTC, swhook52 commented on TravelTrack-API.Project/Controllers/TripsController.cs
> +            return new ObjectResult(e.Response); // other (e.g. Azure blob throws error)
This should probably return an internal server error but not send a response message back. Sending back raw responses on failures can expose sensitive information. You would log that message to track it. You may want to explore adding Application Insights to your project to track failures in the Azure portal.

2023-02-06 16:28 UTC, jmoran-cei commented on TravelTrack-API.Project/Controllers/TripsController.cs
> +            return new ObjectResult(e.Response); // other (e.g. Azure blob throws error)
I added Application Insights for monitoring and tracking my API. I implemented the logger in my controllers for tracking any unexpected exceptions.

2023-02-07 14:29 UTC, swhook52 approved these changes

2023-02-07 14:29 UTC, swhook52 commented on TravelTrack-API.Project/Services/TripService.cs
> +        MemoryStream ms = new MemoryStream();
This should be wrapped in a using block to be sure that it calls destroy

2023-02-07 14:29 UTC, merged